### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LucasRibeiro36** [L3afMe/Gmailnator.py#1]
Traceback (most recent call last):
  File "C:/Users/lucas/PycharmProject/iptvlistgeneratr/teste.py", line 14, in <module>
    print(f'Full body: {gmailnator.get_message(mail["link"], csrf_token)}')
  File "C:\Users\lucas\PycharmProject\iptvlistgeneratr\venv\lib\site-packages\gmailnator\init.py", line 175, in get_message
    return res.text.split('< hr />')[1]
IndexError: list index out of range

ignore space in tag html

**Comment by L3afMe** [comment]
What was the content of the email you were trying to get so I can reproduce this issue?

**Comment by LucasRibeiro-coder** [comment]
any content is showing this error

**Comment by bgbusted** [comment]
The library has updated now, there is a new way of approaching the code, at-least for now.

DONT FORGET TO UPDATE YOUR GMAILNATOR 
```shell
pip install -U git+git://github.com/L3afMe/Gmailnator.py.git
```


 ```python
   from gmailnator import Gmailnator
   Gmailnator = Gmailnator()
   gmailEmail = Gmailnator.getEmail()

   print(gmailEmail)
   print(Gmailnator.receiveInbox())
```
